// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_piloto_novato = "CggI49nPxHEQAhAB"; // <GPGSID>
        public const string achievement_leyenda_del_cosmos = "CggI49nPxHEQAhAF"; // <GPGSID>
        public const string achievement_astronauta_hbil = "CggI49nPxHEQAhAD"; // <GPGSID>
        public const string achievement_una_racha_codiciosa = "CggI49nPxHEQAhAK"; // <GPGSID>
        public const string achievement_gran_persistencia = "CggI49nPxHEQAhAR"; // <GPGSID>
        public const string achievement_oso_orbital = "CggI49nPxHEQAhAU"; // <GPGSID>
        public const string achievement_el_gato_estrellado = "CggI49nPxHEQAhAP"; // <GPGSID>
        public const string achievement_un_vuelo_demasiado_corto = "CggI49nPxHEQAhAS"; // <GPGSID>
        public const string achievement_con_los_bolsillos_llenos = "CggI49nPxHEQAhAI"; // <GPGSID>
        public const string achievement_coleccionista_de_la_moda = "CggI49nPxHEQAhAO"; // <GPGSID>
        public const string achievement_magnate_de_la_galaxia = "CggI49nPxHEQAhAJ"; // <GPGSID>
        public const string achievement_muuuuuy_alto = "CggI49nPxHEQAhAT"; // <GPGSID>
        public const string achievement_fiebre_de_cristal = "CggI49nPxHEQAhAL"; // <GPGSID>
        public const string achievement_un_cambio_de_look = "CggI49nPxHEQAhAN"; // <GPGSID>
        public const string achievement_agujero_negro = "CggI49nPxHEQAhAG"; // <GPGSID>
        public const string achievement_patrocinador = "CggI49nPxHEQAhAQ"; // <GPGSID>
        public const string achievement_a_la_velocidad_de_la_luz = "CggI49nPxHEQAhAH"; // <GPGSID>
        public const string achievement_capitn_estelar = "CggI49nPxHEQAhAE"; // <GPGSID>
        public const string achievement_primeros_pasos = "CggI49nPxHEQAhAC"; // <GPGSID>
        public const string achievement_varo_despistado = "CggI49nPxHEQAhAM"; // <GPGSID>

}

